blank_issues_enabled: true
contact_links:
  - name: Ragdoll Support
    url: https://t.me/RagdollSupportChat
    about: Please drop your doubts or queries there for an immediate response.
  - name: Documentation
    url: https://ultroid.tech/
    about: Basic documentation for setting up.
